// 权威资料来源。评分规则中的每一条都通过 source id 指向这里。

export interface Source {
  id: string;
  org: string;
  title: string;
  year: string;
  url: string;
}

export const SOURCES: Source[] = [
  {
    id: "nasem_dri",
    org: "NASEM / NIH ODS",
    title: "Dietary Reference Intakes (DRI) Summary Tables — RDA/AI/UL/AMDR",
    year: "1997–2023",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK545442/",
  },
  {
    id: "nasem_na_k",
    org: "NASEM",
    title: "Dietary Reference Intakes for Sodium and Potassium (AI & CDRR)",
    year: "2019",
    url: "https://nap.nationalacademies.org/catalog/25353",
  },
  {
    id: "nasem_energy",
    org: "NASEM",
    title: "Dietary Reference Intakes for Energy (EER equations by PAL category)",
    year: "2023",
    url: "https://www.nationalacademies.org/read/26818/chapter/2",
  },
  {
    id: "dga_2020",
    org: "USDA & HHS",
    title: "Dietary Guidelines for Americans, 2020–2025 (added sugars <10% kcal; alcohol ≤2 drinks men / ≤1 women)",
    year: "2020",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8713704/",
  },
  {
    id: "dga_2025",
    org: "USDA & HHS",
    title: "Dietary Guidelines for Americans, 2025–2030 (protein 1.2–1.6 g/kg; ≤10 g added sugars per meal; sat fat ≤10% kcal; sodium <2,300 mg)",
    year: "2026",
    url: "https://cdn.realfood.gov/DGA.pdf",
  },
  {
    id: "hei_2020",
    org: "USDA FNS / NCI",
    title: "Healthy Eating Index-2020 (HEI-2020) components and scoring standards",
    year: "2023",
    url: "https://epi.grants.cancer.gov/hei/developing.html",
  },
  {
    id: "fda_dv",
    org: "FDA",
    title: "Daily Value on the Nutrition and Supplement Facts Labels",
    year: "2016/2020",
    url: "https://www.fda.gov/food/nutrition-facts-label/daily-value-nutrition-and-supplement-facts-labels",
  },
  {
    id: "aha_sugar",
    org: "American Heart Association",
    title: "Added Sugars — daily limits (25 g women / 36 g men / 25 g children)",
    year: "2009/2016",
    url: "https://www.heart.org/en/healthy-living/healthy-eating/eat-smart/sugar/added-sugars",
  },
  {
    id: "aha_sodium",
    org: "American Heart Association",
    title: "How much sodium should I eat per day? (ideal ≤1,500 mg)",
    year: "2021",
    url: "https://www.heart.org/en/healthy-living/healthy-eating/eat-smart/sodium/how-much-sodium-should-i-eat-per-day",
  },
  {
    id: "aha_satfat",
    org: "American Heart Association",
    title: "Saturated Fat (aim for 5–6% of calories when lowering LDL)",
    year: "2021",
    url: "https://www.heart.org/en/healthy-living/healthy-eating/eat-smart/fats/saturated-fats",
  },
  {
    id: "who_trans",
    org: "WHO",
    title: "Trans fat: < 1% of total energy intake",
    year: "2018",
    url: "https://www.who.int/news-room/fact-sheets/detail/trans-fat",
  },
  {
    id: "fda_caffeine",
    org: "FDA",
    title: "Spilling the Beans: How Much Caffeine is Too Much? (400 mg/day adults)",
    year: "2024",
    url: "https://www.fda.gov/consumers/consumer-updates/spilling-beans-how-much-caffeine-too-much",
  },
  {
    id: "acog_caffeine",
    org: "ACOG",
    title: "Moderate Caffeine Consumption During Pregnancy (< 200 mg/day)",
    year: "2020",
    url: "https://www.acog.org/clinical/clinical-guidance/committee-opinion/articles/2010/08/moderate-caffeine-consumption-during-pregnancy",
  },
  {
    id: "hc_caffeine",
    org: "Health Canada",
    title: "Caffeine in Foods — children & adolescents 2.5 mg/kg bw/day",
    year: "2022",
    url: "https://www.canada.ca/en/health-canada/services/food-nutrition/food-safety/food-additives/caffeine-foods.html",
  },
  {
    id: "niaaa_drink",
    org: "NIAAA / NIH",
    title: "What Is A Standard Drink? (14 g pure alcohol; heavy drinking: men ≥15/week, women ≥8/week)",
    year: "2024",
    url: "https://www.niaaa.nih.gov/alcohols-effects-health/what-standard-drink",
  },
  {
    id: "iarc_list",
    org: "IARC / WHO",
    title: "Agents Classified by the IARC Monographs, Volumes 1–139",
    year: "2026",
    url: "https://monographs.iarc.who.int/agents-classified-by-the-iarc/",
  },
  {
    id: "iarc_114",
    org: "IARC / WHO",
    title: "Monograph 114: Red Meat and Processed Meat (processed meat Group 1, red meat Group 2A)",
    year: "2015/2018",
    url: "https://www.iarc.who.int/wp-content/uploads/2018/07/pr240_E.pdf",
  },
  {
    id: "iarc_qa_meat",
    org: "WHO",
    title: "Cancer: Carcinogenicity of the consumption of red meat and processed meat (Q&A; 50 g/day → +18% colorectal cancer)",
    year: "2015",
    url: "https://www.who.int/news-room/questions-and-answers/item/cancer-carcinogenicity-of-the-consumption-of-red-meat-and-processed-meat",
  },
  {
    id: "wcrf",
    org: "WCRF / AICR",
    title: "Cancer Prevention Recommendations (limit red meat to ~350–500 g cooked/week; eat little if any processed meat)",
    year: "2018",
    url: "https://www.wcrf.org/research-policy/evidence-for-our-recommendations/limit-red-processed-meat/",
  },
  {
    id: "iarc_hot_bev",
    org: "IARC / WHO",
    title: "Monograph 116: Drinking very hot beverages (> 65 °C) — Group 2A",
    year: "2016/2018",
    url: "https://publications.iarc.who.int/566",
  },
  {
    id: "iarc_aspartame",
    org: "IARC & JECFA / WHO",
    title: "Aspartame hazard (Group 2B) and risk assessment (ADI 40 mg/kg bw/day)",
    year: "2023",
    url: "https://www.who.int/news/item/14-07-2023-aspartame-hazard-and-risk-assessment-results-released",
  },
  {
    id: "fda_fish",
    org: "FDA / EPA",
    title: "Advice about Eating Fish (choices to avoid: highest mercury)",
    year: "2021",
    url: "https://www.fda.gov/food/consumers/advice-about-eating-fish",
  },
  {
    id: "fda_acrylamide",
    org: "FDA",
    title: "Acrylamide Questions and Answers",
    year: "2022",
    url: "https://www.fda.gov/food/process-contaminants-food/acrylamide-questions-and-answers",
  },
  {
    id: "nci_hca_pah",
    org: "National Cancer Institute",
    title: "Chemicals in Meat Cooked at High Temperatures and Cancer Risk (HCAs & PAHs)",
    year: "2017",
    url: "https://www.cancer.gov/about-cancer/causes-prevention/risk/diet/cooked-meats-fact-sheet",
  },
  {
    id: "pag_2018",
    org: "HHS",
    title: "Physical Activity Guidelines for Americans, 2nd edition (150–300 min moderate / 75–150 min vigorous per week)",
    year: "2018",
    url: "https://odphp.health.gov/our-work/nutrition-physical-activity/physical-activity-guidelines/current-guidelines",
  },
  {
    id: "compendium_2024",
    org: "Herrmann SD et al.",
    title: "2024 Adult Compendium of Physical Activities (MET values)",
    year: "2024",
    url: "https://pacompendium.com/adult-compendium/",
  },
  {
    id: "mifflin",
    org: "Mifflin MD, St Jeor ST et al. (Am J Clin Nutr)",
    title: "A new predictive equation for resting energy expenditure in healthy individuals",
    year: "1990",
    url: "https://pubmed.ncbi.nlm.nih.gov/2305711/",
  },
  {
    id: "nova",
    org: "Monteiro CA et al. (Public Health Nutr)",
    title: "The UN Decade of Nutrition, the NOVA food classification and the trouble with ultra-processing",
    year: "2018",
    url: "https://pubmed.ncbi.nlm.nih.gov/28322183/",
  },
  {
    id: "cdc_weight",
    org: "CDC",
    title: "Losing Weight — gradual, steady loss of 1–2 lb (0.5–1 kg) per week",
    year: "2024",
    url: "https://www.cdc.gov/healthy-weight-growth/losing-weight/index.html",
  },
  {
    id: "nhlbi_bmi",
    org: "NIH NHLBI / CDC",
    title: "Adult BMI categories",
    year: "2024",
    url: "https://www.cdc.gov/bmi/adult-calculator/bmi-categories.html",
  },
  {
    id: "hei_us_mean",
    org: "USDA FNS / CNPP",
    title: "HEI Scores for Americans (HEI-2020 total for ages 2+, NHANES 2017–2018: 58)",
    year: "2023",
    url: "https://www.fns.usda.gov/cnpp/hei-scores-americans",
  },
  {
    id: "mar",
    org: "Arimond et al., J Nutr / FAO",
    title: "Micronutrient adequacy: NAR = min(intake/RDA, 1), MAR = mean NAR of 11 micronutrients (basis of FAO MDD-W)",
    year: "2010",
    url: "https://doi.org/10.3945/jn.110.123414",
  },
  {
    id: "le8",
    org: "American Heart Association",
    title: "Life's Essential 8: Updating and Enhancing the AHA's Construct of Cardiovascular Health (Lloyd-Jones et al., Circulation 2022;146:e18–e43)",
    year: "2022",
    url: "https://doi.org/10.1161/CIR.0000000000001078",
  },
  {
    id: "mepa",
    org: "Cerwinske et al., J Hum Nutr Diet",
    title: "Evaluation of a dietary screener: the Mediterranean Eating Pattern for Americans (MEPA) tool — LE8 individual diet metric",
    year: "2017",
    url: "https://doi.org/10.1111/jhn.12451",
  },
  {
    id: "wcrf_score",
    org: "Shams-White et al., Nutrients",
    title: "Operationalizing the 2018 WCRF/AICR Cancer Prevention Recommendations: A Standardized Scoring System",
    year: "2019",
    url: "https://doi.org/10.3390/nu11071572",
  },
  {
    id: "system",
    org: "本系统",
    title: "本系统设定的阈值（无权威数值时的保守折中，已在规则中注明）",
    year: "2026",
    url: "",
  },
];

export const SOURCE_MAP: Record<string, Source> = Object.fromEntries(SOURCES.map((s) => [s.id, s]));
